### ISSUE TITLE
Question: are my contacts stored on the server indefinitely?

### ISSUE THREAD

**Issue by mak448a** [signalapp/ContactDiscoveryService-Icelake#3]
This might not be the right place to ask, but are a hash of my contacts stored indefinitely on the server’s Secure Enclave? I’d like to have a way to delete my address book from it, if so. Thank you!

**Comment by ripple-cny** [comment]
From my understanding, all it does is compare your contacts to ones stored in the enclave so you know which of your contacts are on Signal.  When you register, you are added to the enclave. So, it stores the basic account information (not all of the account information) in the enclave.  Once you register, it can compare who is using Signal to your contacts.  It does not permanently store a list of your specific contacts.  Does that make sense?

**Comment by mak448a** [comment]
So it only sends the contacts for verification and then deletes it?

**Comment by jgnoonan** [comment]
Correct.  It's primary use is to help you find other users to chat with.  You can search, or you can allow it to use your contacts just to search if they already have Signal accounts.  If they do, the app lets you know so you can connect with them.
